tarting Container

Configured admin IDs: []

Traceback (most recent call last):

  File "/app/main.py", line 40, in <module>

    asyncio.run(main())

  File "/root/.nix-profile/lib/python3.12/asyncio/runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/asyncio/runners.py", line 118, in run

    return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/main.py", line 20, in main

    bot = Bot(token=BOT_TOKEN)

          ^^^^^^^^^^^^^^^^^^^^

^^^

  File "/root/.nix-profile/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 266, in __init__

    validate_token(token)

  File "/opt/venv/lib/python3.12/site-packages/aiogram/utils/token.py", line 17, in validate_token

    raise TokenValidationError(

aiogram.utils.token.TokenValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.

Configured admin IDs: []

Traceback (most recent call last):

  File "/app/main.py", line 40, in <module>

    asyncio.run(main())

  File "/root/.nix-profile/lib/python3.12/asyncio/runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/asyncio/runners.py", line 118, in run

    return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "/app/main.py", line 20, in main

    bot = Bot(token=BOT_TOKEN)

          ^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 266, in __init__

    validate_token(token)

  File "/opt/venv/lib/python3.12/site-packages/aiogram/utils/token.py", line 17, in validate_token

    raise TokenValidationError(

aiogram.utils.token.TokenValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.

Configured admin IDs: []

Traceback (most recent call last):

  File "/app/main.py", line 40, in <module>

    asyncio.run(main())

  File "/root/.nix-profile/lib/python3.12/asyncio/runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/asyncio/runners.py", line 118, in run

    return self._loop.run_until_complete(task)
